// <auto-generated />
namespace Alman.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InitialPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201502271802031_InitialPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
